<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Customer\ViewModel\Address\RegionProvider $regionProvider */
/** @var \TheITNerd\Core\Helper\Config $helper */
$regionProvider = $block->getRegionProvider();
$helper = $this->helper('TheITNerd\Core\Helper\Config');
$isSearchEnabled = $helper->isEnabled() ? 'true' : 'false';
?>
<script type="text/x-magento-init">
{
    "#telephone": {
        "TheITNerd_Core/js/inputMask": {
            "mask": "(00) 0000-00009"
        }
    },
    "#zip": {
        "TheITNerd_Core/js/postcode": {
            "mask": "00000-000",
            "regionJson": <?= $regionProvider->getRegionJson() ?>,
            "isAddressSearchEnabled": <?= $isSearchEnabled ?>
        }
    },
    "#vat_id": {
        "TheITNerd_Brasil/js/cpfCnpjField": {}
    }
}
</script>
