<?php

use Magento\Customer\Block\Widget\Gender;
use Magento\Customer\Block\Widget\Name;
use Magento\Company\Block\Company\Account\Create;
use Magento\Directory\Helper\Data as DirectoryHelper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/**
 * Create account form template
 *
 * @var Create $block
 * @var SecureHtmlRenderer $secureRenderer
 */

/** @var \Magento\Framework\Escaper $escaper */

/** @var \TheITNerd\Brasil\Helper\Address $customAddressHelper */
$customAddressHelper = $this->helper(\TheITNerd\Brasil\Helper\Address::class);
?>
<form class="form create account form-create-account"
      action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      autocomplete="off">
    <?= $block->getBlockHtml('formkey') ?>
    <fieldset class="fieldset info">
        <legend class="legend"><span><?= $block->escapeHtml(__('Company Information')) ?></span></legend><br>
        <div class="field company-name _required">
            <label class="label" for="company_name">
                <span><?= $block->escapeHtml(__('Company Name')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[company_name]" id="company_name"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Company Name')) ?>"
                       class="input-text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field legal-name">
            <label class="label" for="legal_name">
                <span><?= $block->escapeHtml(__('Company Legal Name')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[legal_name]" id="legal_name"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Company Legal Name')) ?>"
                       class="input-text">
            </div>
        </div>
        <div class="field company-email _required">
            <label class="label" for="company_email">
                <span><?= $block->escapeHtml(__('Company Email')) ?></span>
            </label>
            <div class="control">
                <input type="email" name="company[company_email]" id="company_email"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Company Email')) ?>"
                       class="input-text"
                       data-role="email"
                       data-async-is-valid="true"
                       data-mage-init='{"Magento_Company/js/form/element/async-validation": {
                            "name": "company_email",
                            "validateUrl": "<?= $block->escapeUrl($block->getUrl('company/account/validate')) ?>"
                       }}'
                       data-validate="{required:true, 'validate-email': true, 'validate-async-company-email': true}">
            </div>
        </div>
        <div class="field vat-tax-id">
            <label class="label" for="vat_tax_id">
                <span><?= $block->escapeHtml(__('VAT/TAX ID')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[vat_tax_id]" id="vat_tax_id"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('VAT/TAX ID')) ?>"
                       class="input-text">
            </div>
        </div>
        <div class="field reseller-id">
            <label class="label" for="reseller_id">
                <span><?= $block->escapeHtml(__('Re-seller ID')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[reseller_id]" id="reseller_id"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Re-seller ID')) ?>"
                       class="input-text">
            </div>
        </div>
    </fieldset>

    <fieldset class="fieldset info">
        <legend class="legend"><span><?= $block->escapeHtml(__('Legal Address')) ?></span></legend><br>
        <div class="field postcode required">
            <label class="label" for="postcode">
                <span><?= $block->escapeHtml(__('ZIP/Postal Code')) ?></span>
            </label>
            <div class="control">
                <?php $postcodeClass = $block->escapeHtmlAttr($block->getAttributeValidationClass('postcode')) ?>
                <input type="text" name="company[postcode]" id="postcode"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('ZIP/Postal Code')) ?>"
                       class="input-text validate-zip-international <?= /* @noEscape */ $postcodeClass ?>"
                       data-validate="{'required':true, 'validate-zip-international':true}" />
            </div>
        </div>

        <?php for ($_i = 0, $_n = $customAddressHelper->companyAddressGetStreetLines(); $_i < $_n; $_i++): ?>
        <div class="field street <?= $customAddressHelper->getWrapperValidationClass($_i) ?>">
            <label class="label" for="street<?= /* @noEscape */ $_i ?>">
                <span><?= $escaper->escapeHtml(__($customAddressHelper->getFieldLabel($_i))) ?></span>
            </label>
            <div class="control">
                <input type="text"
                       name="company[street][<?= /* @noEscape */ $_i ?>]"
                       value="<?= $escaper->escapeHtml($block->getStreetLine($_i + 1)) ?>"
                       title="<?= /* @noEscape */ $customAddressHelper->getFieldLabel($_i) ?>"
                       id="street<?= /* @noEscape */ $_i ?>"
                       class="input-text <?= $customAddressHelper->getFieldValidationClass($_i) ?>">
            </div>
        </div>
        <?php endfor; ?>

        <div class="field city _required">
            <label class="label" for="city">
                <span><?= $block->escapeHtml(__('City')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[city]" id="city"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                       class="input-text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field country_id _required">
            <label class="label" for="country_id">
                <span><?= $block->escapeHtml(__('Country')) ?></span>
            </label>
            <div class="control _required">
                <?php $countryValue = $block->getDefaultCountryId(); ?>
                <select name="company[country_id]" id="country_id"
                        class="select"
                        title="<?= $block->escapeHtmlAttr(__('Country')) ?>"
                        data-validate="{required:true}">
                    <option value=""><?= $block->escapeHtml(__('Please select an option.')) ?></option>
                    <?php $countries = $block->getCountriesList(); ?>
                    <?php foreach ($countries as $countryCode => $country): ?>
                        <option value="<?= $block->escapeHtmlAttr($countryCode) ?>"
                            <?= ($countryCode == $countryValue) ? ' selected' : '' ;?>>
                            <?= $block->escapeHtml($country) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="field region-id required">
            <label class="label" for="region_id">
                <span><?= $block->escapeHtml(__('State/Province')) ?></span>
            </label>
            <div class="control _required">
                <?php $message = $block->escapeHtml(__('Please select a region, state or province.')) ?>
                <select name="company[region_id]" id="region_id" data-validate="{required:true}" class="select">
                    <option value=""><?= /* @noEscape */ $message ?></option>
                </select>
                <input type="text" id="region" name="company[region]"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
                       class="input-text no-display"">
            </div>
        </div>

        <div class="field telephone _required">
            <label class="label" for="telephone">
                <span><?= $block->escapeHtml(__('Phone Number')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[telephone]" id="telephone"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                       class="input-text" data-validate="{required:true}">
            </div>
        </div>
    </fieldset>

    <fieldset class="fieldset create info">
        <legend class="legend"><span><?= $block->escapeHtml(__('Company Administrator')) ?></span></legend><br>

        <div class="field legal-name">
            <label class="label" for="job_title">
                <span><?= $block->escapeHtml(__('Job Title')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[job_title]" id="job_title"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Job Title')) ?>"
                       class="input-text">
            </div>
        </div>

        <div class="field required">
            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="customer[email]"
                       autocomplete="email"
                       id="email_address"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       class="input-text"
                       data-async-is-valid="true"
                       data-mage-init='{"Magento_Company/js/form/element/async-validation": {
                            "name": "customer_email",
                            "validateUrl": "<?= $block->escapeUrl($block->getUrl('company/account/validate')) ?>"
                       }}'
                       data-validate="{required:true, 'validate-email':true, 'validate-async-customer-email': true}">
            </div>
        </div>

        <?= $block->getLayout()->createBlock(Name::class)
            ->setFieldNameFormat('customer[%s]')
            ->setObject($block->getFormData())
            ->setNoWrap(true)
            ->setForceUseCustomerAttributes(true)
            ->toHtml() ?>

        <?= $block->getLayout()->createBlock(Gender::class)
            ->setFieldNameFormat('customer[%s]')
            ->setGender($block->getFormData()->getGender())
            ->toHtml() ?>

        <?php $userDefinedAttributes = $block->getLayout()->getBlock('customer_form_user_attributes'); ?>
        <?php if ($userDefinedAttributes): ?>
            <?php $userDefinedAttributes->setFieldNameFormat('customer[%1$s]'); ?>
            <?= $userDefinedAttributes->toHtml() ?>
        <?php endif; ?>

        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>

</form>
<?php $scriptString = <<<script
    require([
        'jquery',
        'mage/mage'
    ], function($) {
        var dataForm = $('#form-validate');

        dataForm.mage('validation', {
            ignore: ':hidden',
        }).find('input:text').attr('autocomplete', 'off');
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>

<?php
/** @var DirectoryHelper $directoryDataHelper */
$directoryDataHelper = $block->getData('directoryDataHelper');
$countries = $directoryDataHelper->getCountriesWithOptionalZip(true);
/** @var \Magento\Company\ViewModel\Address\RegionProvider $regionProvider */
$regionProvider = $block->getRegionProvider(); ?>

<script type="text/x-magento-init">
    {
        "#country_id": {
            "directoryRegionUpdater": {
                "optionalRegionAllowed": <?= $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $regionProvider->getRegionJson(); ?>,
                "defaultRegion": "",
                "countriesWithOptionalZip": <?= /* @noEscape */ $countries ?>
            }
        },
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "form-validate"
            }
        }
    }
</script>
