<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Customer\ViewModel\Address\RegionProvider $regionProvider */
$regionProvider = $block->getRegionProvider();
?>
<script type="text/x-magento-init">
{
    "#telephone": {
        "TheITNerd_Core/js/inputMask": {
            "mask": "(00) 0000-00009"
        }
    },
    "#postcode": {
        "TheITNerd_Core/js/postcode": {
            "mask": "00000-000",
            "regionJson": <?= $regionProvider->getRegionJson() ?>,
            "addressFields": {
                "street": "[name='company[street][0]']",
                "neighborhood": "[name='company[street][3]']",
                "city": "[name='company[city]']",
                "region_id": "[name='company[region_id]']",
                "region": "[name='company[region]']",
                "country": "[name='company[country_id]']"
            }
        }
    },
    "#vat_tax_id": {
        "TheITNerd_Brasil/js/cpfCnpjField": {
            "mask": "00000-000"
        }
    },
    "#vat_tax_id": {
        "TheITNerd_Brasil/js/cpfCnpjField": {}
    }
}
</script>
